#菜单
menu:
  Home: /
  Post: /post

#社交链接
link:
  - 
    name: Github
    url: 
    icon: github2
  - 
    name: Telegram
    url: 
    icon: telegram
  - 
    name: Twitter
    url: 
    icon: tuitetwitter43
  - 
    name: Discord
    url: 
    icon: discord
  - 
    name: BiliBili
    url: 
    icon: bilibili
  - 
    name: QQ
    url: 
    icon: QQ
  - 
    name: weixin
    url: 
    icon: weixin-copy

#主页介绍
homeIntroduce:
  one: HEXO
  p1: 快速、简洁且高效的博客框架
  p2: 基于Node.js的静态网站生成器，简单易用支持多种主题插件，具有自动化生成、本地调试和方便部署等特点

# 主页按钮
homeButton:
  -
    name: Get Started
    url: /
    buttonType: brand
  -
    name: View on GitHub
    url: https://github.com/Ririsu-Kokoromu/hexo-theme-vitepress
    buttonType: alt

#主页容器
homeContainer:
  -
    img: img/logo.png
    span: 使用Markdown
    p: 使用Markdown编写你的文章，快速生成HTML网站
  -
    img: img/logo.png
    span: 使用Markdown
    p: 使用Markdown编写你的文章，快速生成HTML网站
  -
    img: img/logo.png
    span: 使用Markdown
    p: 使用Markdown编写你的文章，快速生成HTML网站
  -
    img: img/logo.png
    span: 使用Markdown
    p: 使用Markdown编写你的文章，快速生成HTML网站
  -
    img: img/logo.png
    span: 使用Markdown
    p: 使用Markdown编写你的文章，快速生成HTML网站
  -
    img: img/logo.png
    span: 使用Markdown
    p: 使用Markdown编写你的文章，快速生成HTML网站
  -
    img: img/logo.png
    span: 使用Markdown
    p: 使用Markdown编写你的文章，快速生成HTML网站
  -
    img: img/logo.png
    span: 使用Markdown
    p: 使用Markdown编写你的文章，快速生成HTML网站