logo: <%= url_for('img/logo.svg') %>
menu:
  home: /
  categories: /categories
  tags: /tags
  archives: /archives
  post: /post

homeIntroduce:
  one: HEXO
  p1: 快速、简洁且高效的博客框架
  p2: 基于Node.js的静态网站生成器，简单易用支持多种主题插件，具有自动化生成、本地调试和方便部署等特点
  button1: Get Started
  button2: View on GitHub